export const LABORATORY_STEP_NAMES = {
  CREATE_DISCORD_SERVER: 'CREATE_DISCORD_SERVER',
  CREATE_GROUP_ROLES: 'CREATE_GROUP_ROLES',
  CREATE_GROUP_CHANNELS: 'CREATE_GROUP_CHANNELS',
  CREATE_GROUP_REPOS: 'CREATE_GROUP_REPOS',
  APPLY_GROUP_BRANCH_PROTECTIONS: 'APPLY_GROUP_BRANCH_PROTECTIONS',
  SEED_GROUP_CONTENT: 'SEED_GROUP_CONTENT',
} as const;

export type LaboratoryStepName =
  (typeof LABORATORY_STEP_NAMES)[keyof typeof LABORATORY_STEP_NAMES];

export const LABORATORY_STEPS: Array<{ name: LaboratoryStepName }> = [
  { name: LABORATORY_STEP_NAMES.CREATE_DISCORD_SERVER },
  { name: LABORATORY_STEP_NAMES.CREATE_GROUP_ROLES },
  { name: LABORATORY_STEP_NAMES.CREATE_GROUP_CHANNELS },
  { name: LABORATORY_STEP_NAMES.CREATE_GROUP_REPOS },
  { name: LABORATORY_STEP_NAMES.APPLY_GROUP_BRANCH_PROTECTIONS },
  { name: LABORATORY_STEP_NAMES.SEED_GROUP_CONTENT },
];
