export const LECTURE_STEP_NAMES = {
  CREATE_DISCORD_SERVER: 'CREATE_DISCORD_SERVER',
  CREATE_DISCORD_CHANNELS: 'CREATE_DISCORD_CHANNELS',
  CREATE_GITHUB_REPO: 'CREATE_GITHUB_REPO',
  APPLY_BRANCH_PROTECTION: 'APPLY_BRANCH_PROTECTION',
  SEED_GITHUB_CONTENT: 'SEED_GITHUB_CONTENT',
} as const;

export type LectureStepName =
  (typeof LECTURE_STEP_NAMES)[keyof typeof LECTURE_STEP_NAMES];

export const LECTURE_STEPS: Array<{ name: LectureStepName }> = [
  { name: LECTURE_STEP_NAMES.CREATE_DISCORD_SERVER },
  { name: LECTURE_STEP_NAMES.CREATE_DISCORD_CHANNELS },
  { name: LECTURE_STEP_NAMES.CREATE_GITHUB_REPO },
  { name: LECTURE_STEP_NAMES.APPLY_BRANCH_PROTECTION },
  { name: LECTURE_STEP_NAMES.SEED_GITHUB_CONTENT },
];
